///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2022, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Introduction

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Introduction

This module provides integrations between Coherence and the OCI Secrets Service.

The following features are available:

* <<docs/secrets/02_ssl.adoc,Store TLS/SSL keystores, keys and certificates in OCI secrets>>
* <<docs/secrets/03_password_provider.adoc,Store passwords in OCI secrets>>

== Prerequisites

To use the Coherence OCI Secretes integrations in your project there are some prerequisites required.

=== Configuration

The Coherence OCI modules require the OCI APIs to be configured as described in the <<docs/about/02_getting_started.adoc,Getting Started>> guide.

=== Project Dependencies

To use the Coherence OCI Secrets module your project must depend on `coherence.jar` and `coherence-oci-secrets.jar` by adding the following dependency to your project.

[source,xml,subs="attributes+"]
.Maven pom.xml
----
<dependency>
    <groupId>com.oracle.coherence.ce</groupId>
    <artifactId>coherence</artifactId>
    <version>${coherence.version}</version>
</dependency>
<dependency>
    <groupId>com.oracle.coherence</groupId>
    <artifactId>coherence-oci-secrets</artifactId>
    <version>${coherence.oci.version}</version>
</dependency>
----

[source]
.Gradle build.gradle
----
implementation "com.oracle.coherence.ce:coherence:${coherence.version}"
implementation "com.oracle.coherence:coherence-oci-secrets:${coherence.oci.version}"
----

Replacing `${coherence.version}` with the version of Coherence being used and
replacing `${coherence.oci.version}` with the version of the Coherence OCI module you are using.


=== Using Snapshot Builds

The Coherence OCI Integrations publishes builds of the latest code to the Sonatype Maven snapshots repository.
To use Coherence OCI snapshot versions the Sonatype snapshot repository should be added to the application.

For example, to use version 1.0.0-SNAPSHOT of Coherence OCI and 22.06-SNAPSHOT of Coherence CE:

[source,xml]
.pom.xml
----
  <dependencies>
    <dependency>
        <groupId>com.oracle.coherence.ce</groupId>
        <artifactId>coherence</artifactId>
        <version>22.06-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>com.oracle.coherence</groupId>
        <artifactId>coherence-oci-secrets</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
----

