///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2022, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Introduction

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Introduction

This module provides integrations between Coherence and the OCI Secrets Service.

The following features are available:

* <<docs/secrets/02_ssl.adoc,Store TLS/SSL keystores, keys and certificates in OCI secrets>>
* <<docs/secrets/03_password_provider.adoc,Store passwords in OCI secrets>>

== Prerequisites

To use the Coherence OCI Secretes integrations in your project there are some prerequisites required.

=== Configuration

The Coherence OCI modules require the OCI APIs to be configured as described in the <<docs/about/02_getting_started.adoc,Getting Started>> guide.

=== Project Dependencies

To use the Coherence OCI Secrets module your project must depend on `coherence.jar` and `coherence-oci-secrets.jar` by adding the following dependency to your project.

[source,xml,subs="attributes+"]
.Maven pom.xml
----
<dependency>
    <groupId>com.oracle.coherence.ce</groupId>
    <artifactId>coherence</artifactId>
    <version>${coherence.version}</version>
</dependency>
<dependency>
    <groupId>com.oracle.coherence</groupId>
    <artifactId>coherence-oci-secrets</artifactId>
    <version>${coherence.oci.version}</version>
</dependency>
----

[source]
.Gradle build.gradle
----
implementation "com.oracle.coherence.ce:coherence:${coherence.version}"
implementation "com.oracle.coherence:coherence-oci-secrets:${coherence.oci.version}"
----

Replacing `${coherence.version}` with the version of Coherence being used and
replacing `${coherence.oci.version}` with the version of the Coherence OCI module you are using.



