///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Store SSL Keys & Certs in Secrets

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Store SSL Keys & Certs in Secrets

Coherence can be configured to use SSL for secure communication, as described in the
{commercial-docs-base-url}/secure/using-ssl-secure-communication.html#GUID-90E20139-3945-4993-9048-7FBC93B243A3[Using SSL to Secure Communication] section of the Coherence documentation. By default, they keystores, keys or certificates used by Coherence are stored on the file system or classpath of the JVM. The Coherence OCI Secrets module allows keystores, private keys and certificates to be fetched from the OCI Secrets Service instead of requiring them to be pre-installed as files.

The Coherence APIs provide a way to extend Coherence SSL support to load keystores, private keys and certificates using custom loaders. The Coherence OCI Secrets module makes use of these APIs to add custom loaders to load data from the OCI Secret Service. The keystores, private keys and certificates are then never stored on the local file system.

[NOTE]
====
The Coherence OCI Secrets module only fetches keystores, private keys and certificates,
it does not provide an API to upload this data to the OCI Secrets Service.
====

The following files can be retrieved from OCI secrets:

* <<keys,Private Keys>> from Secrets
* <<certs,Certificates>> from Secrets
* <<keystores,Java Keystores>> from Secrets



=== XML Configuration

The Coherence OCI Secrets module provides a number of custom Coherence XML configuration extensions.
To use these additional XML elements, the Coherence OCI custom XML namespace must be added to the Coherence operational configuration file or cache configuration file, as described in the <<docs/about/02_getting_started.adoc,Getting Started>> guide.


[#keys]
== Private Keys in Secrets

If a private key is stored in the OCI Secrets Service, Coherence SSL can be configured to use that private key.
When configuring SSL in Coherence, a `socket-provider` element is added to the operational configuration or cache configuration files.

For example, the XML below configures the socket provider to use a private key located on the file system at `file:/coherence/security/client.pem`

[source,xml]
----
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
              coherence-operational-config.xsd">

  <cluster-config>
    <socket-providers>
      <socket-provider id="mySSLConfig">
         <ssl>
            <protocol>TLS</protocol>
            <identity-manager>
              <key>file:/coherence/security/client.pem</key>
              <cert>file:/coherence/security/client.cert</cert>
            </identity-manager>
            <trust-manager>
              <cert>file:/coherence/security/ca.cert</cert>
            </trust-manager>
         </ssl>
      </socket-provider>
    </socket-providers>
  </cluster-config>
</coherence>
----

Instead of using the file system, the private key in the `file:/coherence/security/client.pem` file can be uploaded to the OCI Secrets Service. The `secrets-key` XML element can then be used to retrieve the provate key from the OCI Secrets Service.

In the example below, the OCI custom namespace has been added to the configuration file. In the `<identity-manager>` section, instead of the `<key>` element, the `<oci:secrets-key>` element is used to specify the OCID of the secret that the private key is stored in.

[source,xml]
----
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                coherence-operational-config.xsd
                class://com.oracle.coherence.oci.config.OCINamespaceHandler
                coherence-oci.xsd">

  <cluster-config>
    <socket-providers>
      <socket-provider id="mySSLConfig">
         <ssl>
            <protocol>TLS</protocol>
            <identity-manager>
              <oci:secrets-key>
                ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a
              </oci:secrets-key>
              <cert>file:/coherence/security/client.cert</cert>
            </identity-manager>
            <trust-manager>
              <cert>file:/coherence/security/ca.cert</cert>
            </trust-manager>
         </ssl>
      </socket-provider>
    </socket-providers>
  </cluster-config>
</coherence>
----

=== Use Secret Names Instead of OCIDs

The default behaviour of the `oci:secrets-key` element is that its content is the OCID of a secret containing a private key PEM file. Alternatively the name of the secret can be used by specifying the `<oci:secret-name>` element as a child of the <oci:secret-key>` element and additionally a compartment OCID using the `<oci:compartment-id>` element.

The example below will use the secret with the name `my-secret-pem` in the OCI compartment with OCID `ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a`.

[source,xml]
----
<identity-manager>
  <oci:secrets-key>
    <oci:secret-name>my-secret-pem</oci:secret-name>
    <oci:compartment-id>
      ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a
    </oci:compartment-id>
  </oci:secrets-key>
  <cert>file:/coherence/security/client.cert</cert>
</identity-manager>
----

If the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are set the `<oci:compartment-id>` element can be omitted, leaving just the `<oci:secret-name>` element:

[source,xml]
----
<identity-manager>
  <oci:secrets-key>
    <oci:secret-name>my-secret-pem</oci:secret-name>
  </oci:secrets-key>
  <cert>file:/coherence/security/client.cert</cert>
</identity-manager>
----

Or alternatively if the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are set the secret name can be specified as the content of the `<oci:secrets-key>` element:

[source,xml]
----
<identity-manager>
  <oci:secrets-key>my-secret-pem</oci:secrets-key>
  <cert>file:/coherence/security/client.cert</cert>
</identity-manager>
----

If the `<oci:secrets-key>` element does not contain a valid OCID, it is assumed to be a secret name, in which case the Compartment OCID must be specified.
If the `<oci:secret-name>` element is used, or if the `<oci:secrets-key>` element is not an OCID and no Compartment OCID is specified or the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are not set, then an exception will be thrown.


[#certs]
== Certificates in Secrets

If a certificate is stored in the OCI Secrets Service, Coherence SSL can be configured to use that certificate.
When configuring SSL in Coherence, a `socket-provider` element is added to the operational configuration or cache configuration files.

For example, the XML below configures the socket provider with an `<identity-manager>` that uses the certificate located on the file system at `file:/coherence/security/client.cert` and a `<trust-manager>` that uses the CA certificate located on the file system at `file:/coherence/security/ca.cert`

[source,xml]
----
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
              coherence-operational-config.xsd">

  <cluster-config>
    <socket-providers>
      <socket-provider id="mySSLConfig">
         <ssl>
            <protocol>TLS</protocol>
            <identity-manager>
              <key>file:/coherence/security/client.pem</key>
              <cert>file:/coherence/security/client.cert</cert>
            </identity-manager>
            <trust-manager>
              <cert>file:/coherence/security/ca.cert</cert>
            </trust-manager>
         </ssl>
      </socket-provider>
    </socket-providers>
  </cluster-config>
</coherence>
----

Instead of using the file system, the certificate files can be uploaded to the OCI Secrets Service. The `secrets-cert` XML element can then be used to retrieve the provate key from the OCI Secrets Service.

In the example below, the OCI custom namespace has been added to the configuration file. In the `<identity-manager>` section, instead of the `<key>` element, the `<oci:secrets-key>` element is used to specify the OCID of the secret that the certificates are stored in.

[source,xml]
----
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                coherence-operational-config.xsd
                class://com.oracle.coherence.oci.config.OCINamespaceHandler
                coherence-oci.xsd">

  <cluster-config>
    <socket-providers>
      <socket-provider id="mySSLConfig">
         <ssl>
            <protocol>TLS</protocol>
            <identity-manager>
              <oci:secrets-key>
                ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a
              </oci:secrets-key>
              <oci:secrets-cert>
                ocid1.secret.oc1..decdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz89
              </oci:secrets-cert>
            </identity-manager>
            <trust-manager>
              <oci:secrets-cert>
                ocid1.secret.oc1..xacdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz37
              </oci:secrets-cert>
            </trust-manager>
         </ssl>
      </socket-provider>
    </socket-providers>
  </cluster-config>
</coherence>
----

=== Use Secret Names Instead of OCIDs

The default behaviour of the `oci:secrets-cert` element is that its content is the OCID of a secret containing the certificate file. Alternatively the name of the secret can be used by specifying the `<oci:secret-name>` element as a child of the <oci:secret-cert>` element and additionally a compartment OCID using the `<oci:compartment-id>` element.

The example below will create a trust manager using the CA certificate from the secret with the name `my-secret-ca-cert` in the OCI compartment with OCID `ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a`.

[source,xml]
----
<trust-manager>
  <oci:secrets-cert>
    <oci:secret-name>my-secret-ca-cert</oci:secret-name>
    <oci:compartment-id>
      ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a
    </oci:compartment-id>
  </oci:secrets-cert>
</trust-manager>
----

If the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are set the `<oci:compartment-id>` element can be omitted, leaving just the `<oci:secret-name>` element:

[source,xml]
----
<trust-manager>
  <oci:secrets-cert>
    <oci:secret-name>my-secret-ca-cert</oci:secret-name>
  </oci:secrets-cert>
</trust-manager>
----

Or alternatively if the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are set the secret name can be specified as the content of the `<oci:secrets-cert>` element:

[source,xml]
----
<trust-manager>
  <oci:secrets-cert>my-secret-ca-cert</oci:secrets-cert>
</trust-manager>
----

If the `<oci:secrets-cert>` element does not contain a valid OCID, it is assumed to be a secret name, in which case the Compartment OCID must be specified.
If the `<oci:secret-name>` element is used, or if the `<oci:secrets-cert>` element is not an OCID and no Compartment OCID is specified or the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are not set, then an exception will be thrown.


[#keystores]
== Keystores in Secrets

Instead of using private keys and certificates files, Coherence can use Java keystores in the `<identity-manager>` and `<trust-manager>` configurations. Normally keystores are loaded from the file system, but using the Coherence SSL extensions, a custom loader can be used to read the keystore from an alternative source. The Coherence OCI Secrets integration provides a custom keystore loader that can load keystore data from a secret stored in the OCI Secrets Service.

For example, the XML below configures the socket provider to use two keystores the file system at `file:/coherence/security/server.jks` and `file:/coherence/security/server-trust.jks`

[source,xml]
----
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                coherence-operational-config.xsd">

  <cluster-config>
    <socket-providers>
      <socket-provider id="mySSLConfig">
         <ssl>
            <protocol>TLS</protocol>
            <identity-manager>
              <keystore>
                <url>file:/coherence/security/server.jks</url>
              </keystore>
            </identity-manager>
            <trust-manager>
              <keystore>
                <url>file:/coherence/security/server-trust.jks</url>
              </keystore>
            </trust-manager>
         </ssl>
      </socket-provider>
    </socket-providers>
  </cluster-config>
</coherence>
----

Instead of using the file system, the two keystores can be uploaded to secrets in the OCI Secrets Service.
Using the Coherence OCI Secrets integration, it is then possible to load the keystores directlry from the secrets using the relevant OCID.

[source,xml]
----
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                coherence-operational-config.xsd
                class://com.oracle.coherence.oci.config.OCINamespaceHandler
                coherence-oci.xsd">

  <cluster-config>
    <socket-providers>
      <socket-provider id="mySSLConfig">
         <ssl>
            <protocol>TLS</protocol>
            <identity-manager>
              <keystore>
                <key-store-loader>
                  <oci:secrets-key-store>
                    ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a
                  </oci:secrets-key-store>
                </key-store-loader>
              </keystore>
            </identity-manager>
            <trust-manager>
              <keystore>
                <key-store-loader>
                  <oci:secrets-key-store>
                    ocid1.secret.oc1..xyzdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglixt5c
                  </oci:secrets-key-store>
                </key-store-loader>
              </keystore>
            </trust-manager>
         </ssl>
      </socket-provider>
    </socket-providers>
  </cluster-config>
</coherence>
----

The keystore for the identity manager will be loaded from the secret with OCID `ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a` and the keystore for the trust manager will be loaded from the secret with OCID `ocid1.secret.oc1..xyzdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglixt5c`.


=== Use Secret Names Instead of OCIDs

The default behaviour of the `oci:secrets-key-store` element is that its content is the OCID of a secret containing the keystore file. Alternatively the name of the secret can be used by specifying the `<oci:secret-name>` element as a child of the <oci:secrets-key-store>` element and additionally a compartment OCID using the `<oci:compartment-id>` element.

The example below will create a trust store using the keystore data from the secret with the name `my-truststore` in the OCI compartment with OCID `ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a`.

[source,xml]
----
<trust-manager>
  <key-store-loader>
    <oci:secrets-key-store>
      <oci:secret-name>my-truststore</oci:secret-name>
      <oci:compartment-id>
        ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a
      </oci:compartment-id>
    </oci:secrets-key-store>
  </key-store-loader>
</trust-manager>
----

If the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are set the `<oci:compartment-id>` element can be omitted, leaving just the `<oci:secret-name>` element:

[source,xml]
----
<trust-manager>
  <key-store-loader>
    <oci:secrets-key-store>
      <oci:secret-name>my-truststore</oci:secret-name>
    </oci:secrets-key-store>
  </key-store-loader>
</trust-manager>
----

Or alternatively if the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are set the secret name can be specified as the content of the `<oci:secrets-key-store>` element:

[source,xml]
----
<trust-manager>
  <key-store-loader>
    <oci:secrets-key-store>my-truststore</oci:secrets-key-store>
  </key-store-loader>
</trust-manager>
----

If the `<oci:secrets-key-store>` element does not contain a valid OCID, it is assumed to be a secret name, in which case the Compartment OCID must be specified.
If the `<oci:secret-name>` element is used, or if the `<oci:secrets-key-store>` element is not an OCID and no Compartment OCID is specified or the `coherence.oci.compartment` system property, or `COHERENCE_OCI_COMPARTMENT` environment variable are not set, then an exception will be thrown.




