///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Store Passwords in Secrets

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Store Passwords in Secrets

Some Coherence configuration elements allow passwords to be specified using a custom `PasswordProvider`, for example when providing TLS key credentials. The Coherence OCI secrets service integrations provide a custom `PasswordProvider` that obtains a password from a secret.

The Coherence OCI XML configuration extensions provide a `secrets-password-provider` element to configure the secret password provider.
The Coherence OCI custom XML namespace must be added to the Coherence operational configuration file or cache configuration file that the password provider is being configured in, as described in the <<docs/about/02_getting_started.adoc,Getting Started>> guide.

With the OCI namespace added, a secret password provider can be used anywhere the Coherence XML uses a `<password-provider>` element, by adding the `<oci:secrets-password-provider>` element as a child of the `<password-provider>` element.

In the example below, the password will come from a secret with the OCID `ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a`.


[source,xml]
----
<password-provider id="secret-password">
  <oci:secrets-password-provider>
    ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a
  </oci:secrets-password-provider>
</password-provider>
----

Alternatively, instead of specifying the OCID of the secret, a combination of a secret name and a Compartment OCID can be used.
In the example below the password will be read from the secret named `foo` in the compartment with the OCID `ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a`.

[source,xml]
----
<password-provider id="secret-password">
  <oci:secrets-password-provider>
    <oci:secret-name>foo</oci:secret-name>
    <oci:compartment-id>
      ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmentxgxkxku5zhmpu35j67hdxvxpglijz4a
    </oci:compartment-id>
  </oci:secrets-password-provider>
</password-provider>
----

A password provider can be added to the Coherence operational configuration file, as shown below:

[source,xml]
.tangosol-coherence-override.xml
----
<?xml version="1.0"?>
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                               coherence-operational-config.xsd
                               class://com.oracle.coherence.oci.config.OCINamespaceHandler
                               coherence-oci.xsd">

  <cluster-config>
    <password-providers>
      <password-provider id="secret-one">
        <oci:secrets-password-provider>
          ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a
        </oci:secrets-password-provider>
      </password-provider>

      <password-provider id="secret-two">
        <oci:secrets-password-provider>
          <oci:secret-name>my-secret</oci:secret-name>
          <oci:compartment-id>
            ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmenttxgxkxku5zhmpu35j67hdxvxpglijz4a
          </oci:compartment-id>
        </oci:secrets-password-provider>
      </password-provider>
    </password-providers>
  </cluster-config>
</coherence>
----

The `secret-one` password provider will retrieve the password from the secret with the OCID `ocid1.secret.oc1..abcdeaaabvmgyifakesecrettxgxkxku5zhmpu35j67hdxvxpglijz4a`

The `secret-two` password provider will retrieve the password from the secret named `my-secret` in the OCI compartment with the OCID `ocid1.compartment.oc1..abcdeaaabvmgyifakecompartmenttxgxkxku5zhmpu35j67hdxvxpglijz4a`.
