///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= OCI Secrets Service Integration

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== OCI Secrets Service Integration

This module provides integrations between Coherence and the OCI Secrets Service.
To use the Coherence OCI Secrets module add the following dependency to your project.

[source,xml,subs="attributes+"]
.Maven pom.xml
----
<dependency>
    <groupId>com.oracle.coherence.ce</groupId>
    <artifactId>coherence</artifactId>
    <version>${coherenceVersion}</version>
</dependency>
<dependency>
    <groupId>com.oracle.coherence</groupId>
    <artifactId>coherence-oci-secrets</artifactId>
    <version>${coherenceOciVersion}</version>
</dependency>
----

[source]
.Gradle build.gradle
----
implementation "com.oracle.coherence.ce:coherence:${coherenceVersion}"
implementation "com.oracle.coherence:coherence-oci-secrets:${coherenceOciVersion}"
----

Replacing `${coherenceVersion}` with the version of Coherence being used and
replacing `${coherenceOciVersion}` with the version of the Coherence OCI module you are using.

== Enabling the OCI XML Configuration Namespace

When adding OCI extensions to a Coherence cache configuration file or operational configuration override file, the custom OCI namespace needs to be added to the root element.

In the cache configuration file, add the `xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"` namespace declaration and add the schema location `class://com.oracle.coherence.oci.config.OCINamespaceHandler coherence-oci.xsd`

[source,xml]
.coherence-cache-config.xml
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config
                                  coherence-cache-config.xsd
                               class://com.oracle.coherence.oci.config.OCINamespaceHandler
                               coherence-oci.xsd">
</cache-config>
----

In the operational override configuration file, add the `xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"` namespace declaration and add the schema location `class://com.oracle.coherence.oci.config.OCINamespaceHandler coherence-oci.xsd`

[source,xml]
.tangosol-coherence-override.xml
----
<?xml version="1.0"?>
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                               coherence-operational-config.xsd
                               class://com.oracle.coherence.oci.config.OCINamespaceHandler
                               coherence-oci.xsd">

</coherence>
----

With the additional namespace added, OCI XML extensions can be added to the configuration files by prefixing the OCI XML elements with `oci:`



== Configure An OCI Secrets PasswordProvider

Some Coherence configuration elements allow passwords to be specified using a custom `PasswordProvider`, for example when providing TLS key credentials. The Coherence OCI secrets service integrations provide a custom `PasswordProvider` that obtains a password from a secret.

With the OCI namespace added as described above, a secret password provider can be used anywhere the Coherence XML expects a `<password-provider>` by using XML like the snippet shown below:

[source,xml]
----
<oci:secrets-password-provider>
  <oci:secret-id>foo</oci:secret-id>
</oci:secrets-password-provider>
----

In the above example, the password will come from a secret with the id `foo`.




For example, a password provider can be added to the operational override file.

[source,xml]
.tangosol-coherence-override.xml
----
<?xml version="1.0"?>
<coherence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
           xmlns:oci="class://com.oracle.coherence.oci.config.OCINamespaceHandler"
           xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config
                               coherence-operational-config.xsd
                               class://com.oracle.coherence.oci.config.OCINamespaceHandler
                               coherence-oci.xsd">

  <cluster-config>
    <password-providers>
      <password-provider id="test-pass">
        <oci:secrets-password-provider>
          <oci:secret-id>foo</oci:secret-id>
        </oci:secrets-password-provider>
      </password-provider>
    </password-providers>
  </cluster-config>
</coherence>
----

== Configure Coherence TLS using OCI Secrets

Since Coherence version 22.06 configuring TLS has become much more flexible and extendable.
Previously Coherence relied on Java KeysStore files to provide the keys and certs used to create an `SSLContext`.
From version 22.06 support for direct use of key and certificate files was added, as well as the ability to configure custom key and certificate loaders, so that they were not tied to the file system.

The Coherence OCI Secrets Service Integration extension adds custom key and certificate loaders that load data directly from secrets. If using password protected encrypted keys or keystores, these passwords can also be stored in secrets.
